name: mlops-drift
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.24.4
  - pandas=1.5.3
  - matplotlib=3.7.5
  - seaborn=0.13.2
  - scikit-learn=1.3.2
  - tensorflow=2.10
  - keras=2.10
  - h5py
  - statsmodels=0.14.1
  - jupyter
  - pip
  - pip:
      - eurybia==1.1.1
      - alibi-detect
      - catboost==1.2.8